-- AlterTable
ALTER TABLE "LeagueMember" ADD COLUMN     "budget" INTEGER NOT NULL DEFAULT 500;

-- AlterTable
ALTER TABLE "SquadPlayer" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "pricePaid" INTEGER NOT NULL DEFAULT 1;
