CREATE TABLE "player_jornada_points" (
    "playerId" INTEGER NOT NULL,
    "season" INTEGER NOT NULL DEFAULT 2025,
    "pointsJ1" INTEGER,
    "pointsJ2" INTEGER,
    "pointsJ3" INTEGER,
    "pointsJ4" INTEGER,
    "pointsJ5" INTEGER,
    "pointsJ6" INTEGER,
    "pointsJ7" INTEGER,
    "pointsJ8" INTEGER,
    "pointsJ9" INTEGER,
    "pointsJ10" INTEGER,
    "pointsJ11" INTEGER,
    "pointsJ12" INTEGER,
    "pointsJ13" INTEGER,
    "pointsJ14" INTEGER,
    "pointsJ15" INTEGER,
    "pointsJ16" INTEGER,
    "pointsJ17" INTEGER,
    "pointsJ18" INTEGER,
    "pointsJ19" INTEGER,
    "pointsJ20" INTEGER,
    "pointsJ21" INTEGER,
    "pointsJ22" INTEGER,
    "pointsJ23" INTEGER,
    "pointsJ24" INTEGER,
    "pointsJ25" INTEGER,
    "pointsJ26" INTEGER,
    "pointsJ27" INTEGER,
    "pointsJ28" INTEGER,
    "pointsJ29" INTEGER,
    "pointsJ30" INTEGER,
    "pointsJ31" INTEGER,
    "pointsJ32" INTEGER,
    "pointsJ33" INTEGER,
    "pointsJ34" INTEGER,
    "pointsJ35" INTEGER,
    "pointsJ36" INTEGER,
    "pointsJ37" INTEGER,
    "pointsJ38" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "player_jornada_points_pkey" PRIMARY KEY ("playerId", "season")
);

ALTER TABLE "player_jornada_points" ADD CONSTRAINT "player_jornada_points_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
