import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const ClasificacionStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  header: {
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 12,
  },
  headerTitle: {
  fontSize: 24,
  fontWeight: '800',
  color: '#cbd5e1',
  letterSpacing: 0.5,
  textTransform: 'uppercase',
  marginTop: 6,
},

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  userBox: {
    width: '100%',
    backgroundColor: '#1a2332',
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 3,
  },
  userRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 56,
  },
  posBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#475569',
  },
  posBadgeFirst: { borderColor: '#f59e0b' },
  posBadgeSecond: { borderColor: '#94a3b8' },
  posBadgeThird: { borderColor: '#b45309' },
  positionText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
  },
  nameText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#cbd5e1',
    textAlign: 'left',
    marginLeft: 6,
  },
  pointsChip: {
    backgroundColor: '#334155',
    borderWidth: 1,
    borderColor: '#475569',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 9999,
    minWidth: 80,
    alignItems: 'center',
  },
  pointsText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#e2e8f0',
    textAlign: 'center',
  },
});
